// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using filmes_series.data.context;

#nullable disable

namespace filmes_series.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220804221641_UserApp")]
    partial class UserApp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("filmes_series.domain.entity.Ator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Atores");
                });

            modelBuilder.Entity("filmes_series.domain.entity.AtorProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ElencoId")
                        .HasColumnType("int");

                    b.Property<int>("ProducoesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElencoId");

                    b.HasIndex("ProducoesId");

                    b.ToTable("AtorProducao");
                });

            modelBuilder.Entity("filmes_series.domain.entity.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ProducaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProducaoId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("filmes_series.domain.entity.Producao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estudio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Producoes");
                });

            modelBuilder.Entity("filmes_series.Domain.Entity.UserApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("UserApps");
                });

            modelBuilder.Entity("filmes_series.domain.entity.AtorProducao", b =>
                {
                    b.HasOne("filmes_series.domain.entity.Ator", "Elenco")
                        .WithMany("AtorProducao")
                        .HasForeignKey("ElencoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("filmes_series.domain.entity.Producao", "Producoes")
                        .WithMany("AtorProducao")
                        .HasForeignKey("ProducoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elenco");

                    b.Navigation("Producoes");
                });

            modelBuilder.Entity("filmes_series.domain.entity.Categoria", b =>
                {
                    b.HasOne("filmes_series.domain.entity.Producao", null)
                        .WithMany("Categorias")
                        .HasForeignKey("ProducaoId");
                });

            modelBuilder.Entity("filmes_series.domain.entity.Ator", b =>
                {
                    b.Navigation("AtorProducao");
                });

            modelBuilder.Entity("filmes_series.domain.entity.Producao", b =>
                {
                    b.Navigation("AtorProducao");

                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
